### ISSUE TITLE
there are difference between code and paper

### ISSUE THREAD

**Issue by Mhttx2016** [maple-research-lab/AdCo#10]
The paper state "we propose to actively train a set of negative examples as a whole in an adversarial fashion,
in contrast to passively queueing the negative samples over minibatches or simply using the other samples from the current minibatch as negatives." but the [code](https://github.com/maple-research-lab/AdCo/blob/b8f749db3e8e075f77ec17f859e1b2793844f5d3/training/train.py#L32)  include samples over minibatches as negative

**Comment by wang3702** [comment]
Thanks a lot for your interest! Actually, when we train the model, it can also work without in-batch negatives. You can simply remove that part and can still yield a similar performance (<=0.5 difference in linear evaluation). We adopt this in code is because with in-batch negative, it's much more stable.
