### ISSUE TITLE
Question about initialization of negative memory buffer

### ISSUE THREAD

**Issue by Z1Wu** [maple-research-lab/AdCo#9]
Thank you for sharing this great work.
I have a question about the initizalition of Memory_Bank in your code. 
https://github.com/maple-research-lab/AdCo/blob/68b27a8c8e464f4b2a6c7c80c036301f46a4aef9/training/train.py#L247 
In this function, you use the ouput of key encoder to initialize the negative samples, as shown in these lines:
https://github.com/maple-research-lab/AdCo/blob/68b27a8c8e464f4b2a6c7c80c036301f46a4aef9/training/train.py#L296-L302
But why do you set the label of this "pretext task" to [0, ... , 0] as shown in the line below:
https://github.com/maple-research-lab/AdCo/blob/68b27a8c8e464f4b2a6c7c80c036301f46a4aef9/training/train.py#L280
And is initialization of negative samples important to the final performance of model ?

**Comment by wang3702** [comment]
Yes. Initialization is the key to have the basis for adversirial training. 
In the initial stage, the memory bank is not related to training. We just used the embeedings from the first few iterations of MoCo pipeline to init the memory bank instead of random embeddings in memory bank.
The pretext task is identical to MoCo, here 0 just indicates the index 0 has its corrssponding positive (an embedding of another view of the same instance).

**Comment by Z1Wu** [comment]
Thank you for the clear explanation.
